// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocolheader.proto

package org.experimental.protobuf;

public final class ProtobufMsg {
  private ProtobufMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gateway_network.ProtocolHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 magic = 1;</code>
     */
    boolean hasMagic();
    /**
     * <code>required int32 magic = 1;</code>
     */
    int getMagic();

    /**
     * <code>required int32 version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <code>required int32 messageId = 3;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required int32 messageId = 3;</code>
     */
    int getMessageId();

    /**
     * <code>required int32 opCode = 4;</code>
     */
    boolean hasOpCode();
    /**
     * <code>required int32 opCode = 4;</code>
     */
    int getOpCode();

    /**
     * <code>optional int32 subCode = 5;</code>
     */
    boolean hasSubCode();
    /**
     * <code>optional int32 subCode = 5;</code>
     */
    int getSubCode();

    /**
     * <code>optional int32 flags = 6;</code>
     */
    boolean hasFlags();
    /**
     * <code>optional int32 flags = 6;</code>
     */
    int getFlags();

    /**
     * <code>optional string senderId = 7;</code>
     */
    boolean hasSenderId();
    /**
     * <code>optional string senderId = 7;</code>
     */
    java.lang.String getSenderId();
    /**
     * <code>optional string senderId = 7;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <code>optional string senderURL = 8;</code>
     */
    boolean hasSenderURL();
    /**
     * <code>optional string senderURL = 8;</code>
     */
    java.lang.String getSenderURL();
    /**
     * <code>optional string senderURL = 8;</code>
     */
    com.google.protobuf.ByteString
        getSenderURLBytes();

    /**
     * <code>optional string targetAddress = 9;</code>
     */
    boolean hasTargetAddress();
    /**
     * <code>optional string targetAddress = 9;</code>
     */
    java.lang.String getTargetAddress();
    /**
     * <code>optional string targetAddress = 9;</code>
     */
    com.google.protobuf.ByteString
        getTargetAddressBytes();
  }
  /**
   * Protobuf type {@code gateway_network.ProtocolHeader}
   */
  public  static final class ProtocolHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gateway_network.ProtocolHeader)
      ProtocolHeaderOrBuilder {
    // Use ProtocolHeader.newBuilder() to construct.
    private ProtocolHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolHeader() {
      magic_ = 0;
      version_ = 0;
      messageId_ = 0;
      opCode_ = 0;
      subCode_ = 0;
      flags_ = 0;
      senderId_ = "";
      senderURL_ = "";
      targetAddress_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              magic_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              messageId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              opCode_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              subCode_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              flags_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              senderId_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              senderURL_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              targetAddress_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_ProtocolHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_ProtocolHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.experimental.protobuf.ProtobufMsg.ProtocolHeader.class, org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder.class);
    }

    private int bitField0_;
    public static final int MAGIC_FIELD_NUMBER = 1;
    private int magic_;
    /**
     * <code>required int32 magic = 1;</code>
     */
    public boolean hasMagic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 magic = 1;</code>
     */
    public int getMagic() {
      return magic_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>required int32 version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 3;
    private int messageId_;
    /**
     * <code>required int32 messageId = 3;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 messageId = 3;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int OPCODE_FIELD_NUMBER = 4;
    private int opCode_;
    /**
     * <code>required int32 opCode = 4;</code>
     */
    public boolean hasOpCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 opCode = 4;</code>
     */
    public int getOpCode() {
      return opCode_;
    }

    public static final int SUBCODE_FIELD_NUMBER = 5;
    private int subCode_;
    /**
     * <code>optional int32 subCode = 5;</code>
     */
    public boolean hasSubCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 subCode = 5;</code>
     */
    public int getSubCode() {
      return subCode_;
    }

    public static final int FLAGS_FIELD_NUMBER = 6;
    private int flags_;
    /**
     * <code>optional int32 flags = 6;</code>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 flags = 6;</code>
     */
    public int getFlags() {
      return flags_;
    }

    public static final int SENDERID_FIELD_NUMBER = 7;
    private volatile java.lang.Object senderId_;
    /**
     * <code>optional string senderId = 7;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string senderId = 7;</code>
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERURL_FIELD_NUMBER = 8;
    private volatile java.lang.Object senderURL_;
    /**
     * <code>optional string senderURL = 8;</code>
     */
    public boolean hasSenderURL() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string senderURL = 8;</code>
     */
    public java.lang.String getSenderURL() {
      java.lang.Object ref = senderURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string senderURL = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSenderURLBytes() {
      java.lang.Object ref = senderURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETADDRESS_FIELD_NUMBER = 9;
    private volatile java.lang.Object targetAddress_;
    /**
     * <code>optional string targetAddress = 9;</code>
     */
    public boolean hasTargetAddress() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string targetAddress = 9;</code>
     */
    public java.lang.String getTargetAddress() {
      java.lang.Object ref = targetAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetAddress = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTargetAddressBytes() {
      java.lang.Object ref = targetAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMagic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, magic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, messageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, opCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, subCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, flags_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, senderId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, senderURL_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, targetAddress_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, magic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, messageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, opCode_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, subCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, flags_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, senderId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, senderURL_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, targetAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.experimental.protobuf.ProtobufMsg.ProtocolHeader)) {
        return super.equals(obj);
      }
      org.experimental.protobuf.ProtobufMsg.ProtocolHeader other = (org.experimental.protobuf.ProtobufMsg.ProtocolHeader) obj;

      boolean result = true;
      result = result && (hasMagic() == other.hasMagic());
      if (hasMagic()) {
        result = result && (getMagic()
            == other.getMagic());
      }
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && (getMessageId()
            == other.getMessageId());
      }
      result = result && (hasOpCode() == other.hasOpCode());
      if (hasOpCode()) {
        result = result && (getOpCode()
            == other.getOpCode());
      }
      result = result && (hasSubCode() == other.hasSubCode());
      if (hasSubCode()) {
        result = result && (getSubCode()
            == other.getSubCode());
      }
      result = result && (hasFlags() == other.hasFlags());
      if (hasFlags()) {
        result = result && (getFlags()
            == other.getFlags());
      }
      result = result && (hasSenderId() == other.hasSenderId());
      if (hasSenderId()) {
        result = result && getSenderId()
            .equals(other.getSenderId());
      }
      result = result && (hasSenderURL() == other.hasSenderURL());
      if (hasSenderURL()) {
        result = result && getSenderURL()
            .equals(other.getSenderURL());
      }
      result = result && (hasTargetAddress() == other.hasTargetAddress());
      if (hasTargetAddress()) {
        result = result && getTargetAddress()
            .equals(other.getTargetAddress());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMagic()) {
        hash = (37 * hash) + MAGIC_FIELD_NUMBER;
        hash = (53 * hash) + getMagic();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageId();
      }
      if (hasOpCode()) {
        hash = (37 * hash) + OPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getOpCode();
      }
      if (hasSubCode()) {
        hash = (37 * hash) + SUBCODE_FIELD_NUMBER;
        hash = (53 * hash) + getSubCode();
      }
      if (hasFlags()) {
        hash = (37 * hash) + FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getFlags();
      }
      if (hasSenderId()) {
        hash = (37 * hash) + SENDERID_FIELD_NUMBER;
        hash = (53 * hash) + getSenderId().hashCode();
      }
      if (hasSenderURL()) {
        hash = (37 * hash) + SENDERURL_FIELD_NUMBER;
        hash = (53 * hash) + getSenderURL().hashCode();
      }
      if (hasTargetAddress()) {
        hash = (37 * hash) + TARGETADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getTargetAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.experimental.protobuf.ProtobufMsg.ProtocolHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gateway_network.ProtocolHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gateway_network.ProtocolHeader)
        org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_ProtocolHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_ProtocolHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.experimental.protobuf.ProtobufMsg.ProtocolHeader.class, org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder.class);
      }

      // Construct using org.experimental.protobuf.ProtobufMsg.ProtocolHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        magic_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        opCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        subCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        senderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        senderURL_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        targetAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_ProtocolHeader_descriptor;
      }

      public org.experimental.protobuf.ProtobufMsg.ProtocolHeader getDefaultInstanceForType() {
        return org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance();
      }

      public org.experimental.protobuf.ProtobufMsg.ProtocolHeader build() {
        org.experimental.protobuf.ProtobufMsg.ProtocolHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.experimental.protobuf.ProtobufMsg.ProtocolHeader buildPartial() {
        org.experimental.protobuf.ProtobufMsg.ProtocolHeader result = new org.experimental.protobuf.ProtobufMsg.ProtocolHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.magic_ = magic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.opCode_ = opCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.subCode_ = subCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.senderURL_ = senderURL_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.targetAddress_ = targetAddress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.experimental.protobuf.ProtobufMsg.ProtocolHeader) {
          return mergeFrom((org.experimental.protobuf.ProtobufMsg.ProtocolHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.experimental.protobuf.ProtobufMsg.ProtocolHeader other) {
        if (other == org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance()) return this;
        if (other.hasMagic()) {
          setMagic(other.getMagic());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasOpCode()) {
          setOpCode(other.getOpCode());
        }
        if (other.hasSubCode()) {
          setSubCode(other.getSubCode());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasSenderId()) {
          bitField0_ |= 0x00000040;
          senderId_ = other.senderId_;
          onChanged();
        }
        if (other.hasSenderURL()) {
          bitField0_ |= 0x00000080;
          senderURL_ = other.senderURL_;
          onChanged();
        }
        if (other.hasTargetAddress()) {
          bitField0_ |= 0x00000100;
          targetAddress_ = other.targetAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMagic()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        if (!hasMessageId()) {
          return false;
        }
        if (!hasOpCode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.experimental.protobuf.ProtobufMsg.ProtocolHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.experimental.protobuf.ProtobufMsg.ProtocolHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int magic_ ;
      /**
       * <code>required int32 magic = 1;</code>
       */
      public boolean hasMagic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 magic = 1;</code>
       */
      public int getMagic() {
        return magic_;
      }
      /**
       * <code>required int32 magic = 1;</code>
       */
      public Builder setMagic(int value) {
        bitField0_ |= 0x00000001;
        magic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 magic = 1;</code>
       */
      public Builder clearMagic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        magic_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required int32 version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private int messageId_ ;
      /**
       * <code>required int32 messageId = 3;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 messageId = 3;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>required int32 messageId = 3;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000004;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 messageId = 3;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int opCode_ ;
      /**
       * <code>required int32 opCode = 4;</code>
       */
      public boolean hasOpCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 opCode = 4;</code>
       */
      public int getOpCode() {
        return opCode_;
      }
      /**
       * <code>required int32 opCode = 4;</code>
       */
      public Builder setOpCode(int value) {
        bitField0_ |= 0x00000008;
        opCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 opCode = 4;</code>
       */
      public Builder clearOpCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        opCode_ = 0;
        onChanged();
        return this;
      }

      private int subCode_ ;
      /**
       * <code>optional int32 subCode = 5;</code>
       */
      public boolean hasSubCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 subCode = 5;</code>
       */
      public int getSubCode() {
        return subCode_;
      }
      /**
       * <code>optional int32 subCode = 5;</code>
       */
      public Builder setSubCode(int value) {
        bitField0_ |= 0x00000010;
        subCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subCode = 5;</code>
       */
      public Builder clearSubCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        subCode_ = 0;
        onChanged();
        return this;
      }

      private int flags_ ;
      /**
       * <code>optional int32 flags = 6;</code>
       */
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 flags = 6;</code>
       */
      public int getFlags() {
        return flags_;
      }
      /**
       * <code>optional int32 flags = 6;</code>
       */
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000020;
        flags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flags = 6;</code>
       */
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000020);
        flags_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object senderId_ = "";
      /**
       * <code>optional string senderId = 7;</code>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public java.lang.String getSenderId() {
        java.lang.Object ref = senderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        java.lang.Object ref = senderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        senderId_ = getDefaultInstance().getSenderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderId = 7;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        senderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderURL_ = "";
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public boolean hasSenderURL() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public java.lang.String getSenderURL() {
        java.lang.Object ref = senderURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderURL_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSenderURLBytes() {
        java.lang.Object ref = senderURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public Builder setSenderURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        senderURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public Builder clearSenderURL() {
        bitField0_ = (bitField0_ & ~0x00000080);
        senderURL_ = getDefaultInstance().getSenderURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string senderURL = 8;</code>
       */
      public Builder setSenderURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        senderURL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetAddress_ = "";
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public boolean hasTargetAddress() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public java.lang.String getTargetAddress() {
        java.lang.Object ref = targetAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTargetAddressBytes() {
        java.lang.Object ref = targetAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public Builder setTargetAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        targetAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public Builder clearTargetAddress() {
        bitField0_ = (bitField0_ & ~0x00000100);
        targetAddress_ = getDefaultInstance().getTargetAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetAddress = 9;</code>
       */
      public Builder setTargetAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        targetAddress_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gateway_network.ProtocolHeader)
    }

    // @@protoc_insertion_point(class_scope:gateway_network.ProtocolHeader)
    private static final org.experimental.protobuf.ProtobufMsg.ProtocolHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.experimental.protobuf.ProtobufMsg.ProtocolHeader();
    }

    public static org.experimental.protobuf.ProtobufMsg.ProtocolHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtocolHeader>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolHeader>() {
      public ProtocolHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtocolHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolHeader> getParserForType() {
      return PARSER;
    }

    public org.experimental.protobuf.ProtobufMsg.ProtocolHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gateway_network.MessageBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes msgBody = 10;</code>
     */
    boolean hasMsgBody();
    /**
     * <code>optional bytes msgBody = 10;</code>
     */
    com.google.protobuf.ByteString getMsgBody();
  }
  /**
   * Protobuf type {@code gateway_network.MessageBody}
   */
  public  static final class MessageBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gateway_network.MessageBody)
      MessageBodyOrBuilder {
    // Use MessageBody.newBuilder() to construct.
    private MessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageBody() {
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 82: {
              bitField0_ |= 0x00000001;
              msgBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_MessageBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_MessageBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.experimental.protobuf.ProtobufMsg.MessageBody.class, org.experimental.protobuf.ProtobufMsg.MessageBody.Builder.class);
    }

    private int bitField0_;
    public static final int MSGBODY_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>optional bytes msgBody = 10;</code>
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes msgBody = 10;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(10, msgBody_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.experimental.protobuf.ProtobufMsg.MessageBody)) {
        return super.equals(obj);
      }
      org.experimental.protobuf.ProtobufMsg.MessageBody other = (org.experimental.protobuf.ProtobufMsg.MessageBody) obj;

      boolean result = true;
      result = result && (hasMsgBody() == other.hasMsgBody());
      if (hasMsgBody()) {
        result = result && getMsgBody()
            .equals(other.getMsgBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsgBody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.MessageBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.experimental.protobuf.ProtobufMsg.MessageBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gateway_network.MessageBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gateway_network.MessageBody)
        org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_MessageBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_MessageBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.experimental.protobuf.ProtobufMsg.MessageBody.class, org.experimental.protobuf.ProtobufMsg.MessageBody.Builder.class);
      }

      // Construct using org.experimental.protobuf.ProtobufMsg.MessageBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_MessageBody_descriptor;
      }

      public org.experimental.protobuf.ProtobufMsg.MessageBody getDefaultInstanceForType() {
        return org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance();
      }

      public org.experimental.protobuf.ProtobufMsg.MessageBody build() {
        org.experimental.protobuf.ProtobufMsg.MessageBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.experimental.protobuf.ProtobufMsg.MessageBody buildPartial() {
        org.experimental.protobuf.ProtobufMsg.MessageBody result = new org.experimental.protobuf.ProtobufMsg.MessageBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgBody_ = msgBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.experimental.protobuf.ProtobufMsg.MessageBody) {
          return mergeFrom((org.experimental.protobuf.ProtobufMsg.MessageBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.experimental.protobuf.ProtobufMsg.MessageBody other) {
        if (other == org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance()) return this;
        if (other.hasMsgBody()) {
          setMsgBody(other.getMsgBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.experimental.protobuf.ProtobufMsg.MessageBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.experimental.protobuf.ProtobufMsg.MessageBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msgBody = 10;</code>
       */
      public boolean hasMsgBody() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes msgBody = 10;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>optional bytes msgBody = 10;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msgBody = 10;</code>
       */
      public Builder clearMsgBody() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gateway_network.MessageBody)
    }

    // @@protoc_insertion_point(class_scope:gateway_network.MessageBody)
    private static final org.experimental.protobuf.ProtobufMsg.MessageBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.experimental.protobuf.ProtobufMsg.MessageBody();
    }

    public static org.experimental.protobuf.ProtobufMsg.MessageBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageBody>
        PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
      public MessageBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBody> getParserForType() {
      return PARSER;
    }

    public org.experimental.protobuf.ProtobufMsg.MessageBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GatewayNetworkMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gateway_network.GatewayNetworkMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    org.experimental.protobuf.ProtobufMsg.ProtocolHeader getHeader();
    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    org.experimental.protobuf.ProtobufMsg.MessageBody getBody();
    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code gateway_network.GatewayNetworkMsg}
   */
  public  static final class GatewayNetworkMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gateway_network.GatewayNetworkMsg)
      GatewayNetworkMsgOrBuilder {
    // Use GatewayNetworkMsg.newBuilder() to construct.
    private GatewayNetworkMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GatewayNetworkMsg() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GatewayNetworkMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(org.experimental.protobuf.ProtobufMsg.ProtocolHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.experimental.protobuf.ProtobufMsg.MessageBody.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(org.experimental.protobuf.ProtobufMsg.MessageBody.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_GatewayNetworkMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_GatewayNetworkMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.class, org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private org.experimental.protobuf.ProtobufMsg.ProtocolHeader header_;
    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    public org.experimental.protobuf.ProtobufMsg.ProtocolHeader getHeader() {
      return header_ == null ? org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>required .gateway_network.ProtocolHeader header = 1;</code>
     */
    public org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance() : header_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private org.experimental.protobuf.ProtobufMsg.MessageBody body_;
    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    public org.experimental.protobuf.ProtobufMsg.MessageBody getBody() {
      return body_ == null ? org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance() : body_;
    }
    /**
     * <code>optional .gateway_network.MessageBody body = 2;</code>
     */
    public org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder getBodyOrBuilder() {
      return body_ == null ? org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance() : body_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getBody());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg)) {
        return super.equals(obj);
      }
      org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg other = (org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gateway_network.GatewayNetworkMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gateway_network.GatewayNetworkMsg)
        org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_GatewayNetworkMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_GatewayNetworkMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.class, org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.Builder.class);
      }

      // Construct using org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.experimental.protobuf.ProtobufMsg.internal_static_gateway_network_GatewayNetworkMsg_descriptor;
      }

      public org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg getDefaultInstanceForType() {
        return org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.getDefaultInstance();
      }

      public org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg build() {
        org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg buildPartial() {
        org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg result = new org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg) {
          return mergeFrom((org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg other) {
        if (other == org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          return false;
        }
        if (!getHeader().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.experimental.protobuf.ProtobufMsg.ProtocolHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.experimental.protobuf.ProtobufMsg.ProtocolHeader, org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder, org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.ProtocolHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public Builder setHeader(org.experimental.protobuf.ProtobufMsg.ProtocolHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public Builder setHeader(
          org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public Builder mergeHeader(org.experimental.protobuf.ProtobufMsg.ProtocolHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != null &&
              header_ != org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance()) {
            header_ =
              org.experimental.protobuf.ProtobufMsg.ProtocolHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              org.experimental.protobuf.ProtobufMsg.ProtocolHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>required .gateway_network.ProtocolHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.experimental.protobuf.ProtobufMsg.ProtocolHeader, org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder, org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.experimental.protobuf.ProtobufMsg.ProtocolHeader, org.experimental.protobuf.ProtobufMsg.ProtocolHeader.Builder, org.experimental.protobuf.ProtobufMsg.ProtocolHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private org.experimental.protobuf.ProtobufMsg.MessageBody body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.experimental.protobuf.ProtobufMsg.MessageBody, org.experimental.protobuf.ProtobufMsg.MessageBody.Builder, org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder> bodyBuilder_;
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.MessageBody getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public Builder setBody(org.experimental.protobuf.ProtobufMsg.MessageBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public Builder setBody(
          org.experimental.protobuf.ProtobufMsg.MessageBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public Builder mergeBody(org.experimental.protobuf.ProtobufMsg.MessageBody value) {
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              body_ != null &&
              body_ != org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance()) {
            body_ =
              org.experimental.protobuf.ProtobufMsg.MessageBody.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.MessageBody.Builder getBodyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      public org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              org.experimental.protobuf.ProtobufMsg.MessageBody.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>optional .gateway_network.MessageBody body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.experimental.protobuf.ProtobufMsg.MessageBody, org.experimental.protobuf.ProtobufMsg.MessageBody.Builder, org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.experimental.protobuf.ProtobufMsg.MessageBody, org.experimental.protobuf.ProtobufMsg.MessageBody.Builder, org.experimental.protobuf.ProtobufMsg.MessageBodyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gateway_network.GatewayNetworkMsg)
    }

    // @@protoc_insertion_point(class_scope:gateway_network.GatewayNetworkMsg)
    private static final org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg();
    }

    public static org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GatewayNetworkMsg>
        PARSER = new com.google.protobuf.AbstractParser<GatewayNetworkMsg>() {
      public GatewayNetworkMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GatewayNetworkMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GatewayNetworkMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GatewayNetworkMsg> getParserForType() {
      return PARSER;
    }

    public org.experimental.protobuf.ProtobufMsg.GatewayNetworkMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gateway_network_ProtocolHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_network_ProtocolHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gateway_network_MessageBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_network_MessageBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gateway_network_GatewayNetworkMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gateway_network_GatewayNetworkMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protocolheader.proto\022\017gateway_network\"" +
      "\257\001\n\016ProtocolHeader\022\r\n\005magic\030\001 \002(\005\022\017\n\007ver" +
      "sion\030\002 \002(\005\022\021\n\tmessageId\030\003 \002(\005\022\016\n\006opCode\030" +
      "\004 \002(\005\022\017\n\007subCode\030\005 \001(\005\022\r\n\005flags\030\006 \001(\005\022\020\n" +
      "\010senderId\030\007 \001(\t\022\021\n\tsenderURL\030\010 \001(\t\022\025\n\rta" +
      "rgetAddress\030\t \001(\t\"\036\n\013MessageBody\022\017\n\007msgB" +
      "ody\030\n \001(\014\"p\n\021GatewayNetworkMsg\022/\n\006header" +
      "\030\001 \002(\0132\037.gateway_network.ProtocolHeader\022" +
      "*\n\004body\030\002 \001(\0132\034.gateway_network.MessageB" +
      "odyB(\n\031org.experimental.protobufB\013Protob",
      "ufMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gateway_network_ProtocolHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gateway_network_ProtocolHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gateway_network_ProtocolHeader_descriptor,
        new java.lang.String[] { "Magic", "Version", "MessageId", "OpCode", "SubCode", "Flags", "SenderId", "SenderURL", "TargetAddress", });
    internal_static_gateway_network_MessageBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gateway_network_MessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gateway_network_MessageBody_descriptor,
        new java.lang.String[] { "MsgBody", });
    internal_static_gateway_network_GatewayNetworkMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gateway_network_GatewayNetworkMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gateway_network_GatewayNetworkMsg_descriptor,
        new java.lang.String[] { "Header", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
